insert into notify (name,title,content) values ('관리자','추석맞이 특가 이벤트 행사','2022년 추석을 맞이하여 특별가격 행사를 진행합니다.');
insert into notify values (default,'관리자','추석맞이 특가 이벤트 행사','2022년 추석을 맞이하여 특별가격 행사를 진행합니다.',default,default,default);
insert into board values (default,'관리맨','게시판 서비스를 시작합니다.','cjsk1126@naver.com','http://blog.daum.net/cjsk1126','이곳은 게시판입니다.',default,default,'192.168.50.20',default,'admin');
insert into testStudent values (default, 1111, 'hkd1234', '홍길동', default);
insert into testStudent values (default, 2222, 'kms1234', '김말숙', 26);
insert into testStudent values (2, 444, 'ohn1234', '오하늘', 30); -- ???
insert into guest values (default,'관리자','cjsk1126@naver.com','blog.daum.net/cjsk1126',default,'192.168.50.20','방명록 서비스를 시작합니다.');
insert into guest values (default,'홍길동','hkd1234@hanmail.net','blog.daum.net/cjsk1126',default,'210.20.54.29','귀사의 번영을 기원합니다.');
insert into member values (default,'admin','1234','관리맨','관리자',default,default,'010-3423-2704','경기도 안성시 공도로 142', 'cjsk1126@naver.com','http://blog.daum.net/cjsk1126','프리랜서','등산/바둑',default,'관리자입니다.',default,default,default,default,default,default,default,default);
insert into schedule value (default, 'hkd1234', '2022-07-29', '모임', '가족회의, 장소:집, 시간:19시');
insert into schedule value (default, 'hkd1234', '2022-08-30', '기타', '아침굽기, 장소:청주의료원, 시간:10시');
insert into schedule value (default, 'hkd1234', '2022-07-29', '모임', '친구생일, 장소:치킨호프, 시간:21시');
insert into schedule value (default, 'hkd1234', '2022-07-25', '학습', '영어회와, 장소:영어학원, 시간:17시');
insert into schedule value (default, 'hkd1234', '2022-07-29', '학습', '객체학습, 장소:도서관, 시간:12시');
insert into schedule value (default, 'hkd1234', '2022-06-25', '모임', '6.25모임, 장소:통일관, 시간:14시');
insert into schedule value (default, 'hkd1234', '2022-08-04', '업무', '주제발표, 장소:회사, 시간:10시');
insert into schedule value (default, 'hkd1234', '2022-07-20', '모임', '가족행사, 장소:집, 시간:19시');
insert into schedule value (default, 'hkd1234', '2022-07-04', '모임', '여행친구, 장소:월드컵호프, 시간:20시');
insert into schedule value (default, 'hkd1234', '2022-07-15', '여행', '정동진 해돋이, 장소:강릉, 시간:05시');
insert into schedule value (default, 'kms1234', '2022-08-15', '모임', '소영이생일파티, 장소:홈파티홀, 시간:15시');
insert into schedule value (default, 'kms1234', '2022-08-29', '여행', '유달산산행, 장소:유달산, 시간:09시');
insert into goods1 values ('전자제품');
insert into goods1 values ('신발류');
insert into goods1 values ('의류');
insert into goods2 values ('전자제품','삼성');
insert into goods2 values ('전자제품','LG');
insert into goods2 values ('전자제품','현대');
insert into goods2 values ('신발류','나이키');
insert into goods2 values ('신발류','아디다스');
insert into goods2 values ('의류','블랙야크');
insert into goods2 values ('의류','K2');
insert into goods2 values ('의류','노스페이스');
insert into goods3 values (default,'전자제품','삼성','냉장고');
insert into goods3 values (default,'전자제품','삼성','에어컨');
insert into goods3 values (default,'전자제품','삼성','세탁기');
insert into goods3 values (default,'전자제품','LG','냉장고');
insert into goods3 values (default,'전자제품','LG','건조기');
insert into goods3 values (default,'전자제품','LG','식기세척기');
insert into goods3 values (default,'전자제품','현대','세탁기');
insert into goods3 values (default,'전자제품','현대','스타일러');
insert into goods3 values (default,'신발류','나이키','운동화');
insert into goods3 values (default,'신발류','나이키','등산화');
insert into goods3 values (default,'신발류','나이키','슬리퍼');
insert into goods3 values (default,'신발류','아디다스','운동화');
insert into goods3 values (default,'신발류','아디다스','축구화');
insert into goods3 values (default,'신발류','아디다스','욕실화');
insert into goods3 values (default,'의류','노스페이스','언더웨어');
insert into goods3 values (default,'의류','노스페이스','바지');
insert into goods3 values (default,'의류','노스페이스','자켓');
insert into goods3 values (default,'의류','블랙야크','자켓');
insert into goods3 values (default,'의류','블랙야크','바지');
insert into goods3 values (default,'의류','블랙야크','상의');
insert into goods3 values (default,'의류','K2','점퍼');
insert into goods3 values (default,'의류','K2','바지');
insert into operatorHashTable2 values ( 1,'0011ABCD');
insert into operatorHashTable2 values ( 2,'0111BADA');
insert into operatorHashTable2 values ( 3,'1211CBAA');
insert into operatorHashTable2 values ( 4,'1311DAAF');
insert into operatorHashTable2 values ( 5,'2411EAAA');
insert into operatorHashTable2 values ( 6,'2511FAAA');
insert into operatorHashTable2 values ( 7,'3611ABDA');
insert into operatorHashTable2 values ( 8,'3711BAAF');
insert into operatorHashTable2 values ( 9,'4811CAAA');
insert into operatorHashTable2 values (10,'4911DAAA');
insert into operatorHashTable2 values (11,'5011EAAA');
insert into operatorHashTable2 values (12,'5111FBDF');
insert into operatorHashTable2 values (13,'6211AAAA');
insert into operatorHashTable2 values (14,'6311BAAA');
insert into operatorHashTable2 values (15,'7411CAAA');
insert into operatorHashTable2 values (16,'7511DAAF');
insert into operatorHashTable2 values (17,'6611EBDA');
insert into operatorHashTable2 values (18,'5711FAAA');
insert into operatorHashTable2 values (19,'4811AAAA');
insert into operatorHashTable2 values (20,'3911BAAF');
insert into operatorHashTable2 values (21,'0011CAAA');
insert into operatorHashTable2 values (22,'0111DBDA');
insert into operatorHashTable2 values (23,'1211EAAA');
insert into operatorHashTable2 values (24,'1311FAAF');
insert into operatorHashTable2 values (25,'2411AAAA');
insert into operatorHashTable2 values (26,'2511BAAA');
insert into operatorHashTable2 values (27,'3611CBDA');
insert into operatorHashTable2 values (28,'3771DAAF');
insert into operatorHashTable2 values (29,'4811EAAA');
insert into operatorHashTable2 values (30,'4911FAAA');
insert into operatorHashTable2 values (31,'5011AAAA');
insert into operatorHashTable2 values (32,'5111BBDF');
insert into operatorHashTable2 values (33,'6211CAAA');
insert into operatorHashTable2 values (34,'6311DAAA');
insert into operatorHashTable2 values (35,'7411EAAA');
insert into operatorHashTable2 values (36,'7511FAAF');
insert into operatorHashTable2 values (37,'6611ABDA');
insert into operatorHashTable2 values (38,'5711BAAA');
insert into operatorHashTable2 values (39,'4811CAAA');
insert into operatorHashTable2 values (40,'3911DAAF');
insert into operatorHashTable2 values (41,'0011EAAA');
insert into operatorHashTable2 values (42,'0111FBDA');
insert into operatorHashTable2 values (43,'1211AAAA');
insert into operatorHashTable2 values (44,'2311BAAF');
insert into operatorHashTable2 values (45,'3411CAAA');
insert into operatorHashTable2 values (46,'4511DAAA');
insert into operatorHashTable2 values (47,'5611EADA');
insert into operatorHashTable2 values (48,'6711FAAF');
insert into operatorHashTable2 values (49,'7811AAAA');
insert into operatorHashTable2 values (50,'3911AAAA');